name: Terraform fmt

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: terraform-fmt-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  terraform-fmt:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        with:
          filters: |
            infra:
              - 'infra/**'

      - if: steps.changes.outputs.infra == 'true'
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: 1.10.0

      - if: steps.changes.outputs.infra == 'true'
        run: terraform fmt -check -recursive infra/
